#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!

sudo apt-get update
sudo apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
